language: python
python:
- "3.6"
- "3.7"
# command to install dependencies
install:
- pip install -r requirements.txt
- sudo apt-get update
- sudo apt-get install install libprotobuf9 libprotobuf-c0
# command to run tests
script:
- python init.py
- pytest
