language: python
python:
- "3.6"

# command to install dependencies
before_install:
- sudo apt-get update
- "sudo chmod 755 utils/install_protobuf.sh"
- "./utils/install_protobuf.sh"
- sudo sh -c "echo '/usr/lib' >> /etc/ld.so.conf.d/lib.conf"
- sudo sh -c "echo '/usr/local/lib' >> /etc/local.conf"
- sudo ldconfig
- export LD_LIBRARY_PATH=/usr/local/lib

install:
- pip install -r requirements.txt
# command to run tests
script:
- python init.py
- pytest
