language: python
python:
- "3.6"
- "3.7"

# command to install dependencies
before_install:
- "sudo chmod 755 utils/install_protobuf.sh"
- "./utils/install_protobuf.sh"

install:
- pip install -r requirements.txt
# command to run tests
script:
- python init.py
- pytest
