
version: 0.6.{build}
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true


environment:
  PYTHON_ARCH: "64"

  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.4"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.9"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "SET PYTHONPATH=%PYTHON%\\Lib\\site-packages;%PYTHONPATH%"
  - python --version

  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python init.py

test_script:
  - pytest --cov=./ --ignore=protobuf-2.6.1/
  - bash <(curl -s https://codecov.io/bash) -c -F carball
