
version: 0.6.{build}
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true


platform:
  - x64

environment:
  matrix:
    - TOXENV: py36
    - TOXENV: py37

install:
  - pip install -r requirements.txt
  - pip install -r requirements-test.txt
  - python init.py

test_script:
  - pytest --cov=./ --ignore=protobuf-2.6.1/
  - bash <(curl -s https://codecov.io/bash) -c -F carball
