
version: 0.6.{build}
skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true


environment:
  matrix:
  - PYTHON: C:\Python37-x64
  - PYTHON: C:\Python36-x64

install:
  - python --version
  - python3 -m pip install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-test.txt
  - python3 init.py

test_script:
  - pytest --cov=./ --ignore=protobuf-2.6.1/
  - bash <(curl -s https://codecov.io/bash) -c -F carball
