name: Benchmarking

on:
  push:
    branches: [ master, div-tests ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install/Update pip and wheel.
      run:
        python -m pip install --upgrade pip &&
        pip install wheel

    - name: Set-up and install protobuf.
      run: chmod 777 ./_travis/install-protoc.sh && ./_travis/install-protoc.sh 2.6.1

    - name: Install dependencies.
      run: pip install -r requirements.txt && pip install -r requirements-test.txt

    - name: Initialise.
      run: python init.py

    - name: Prepare benchmark.
      run: |
        pip install -r requirements.txt && pip install -r requirements-test.txt
        cd carball/tests/benchmarking
        echo === BENCHMARK DIRECTORY ===
        ls -lh
        echo ===========================

    - name: Run benchmark.
      run: |
        cd carball/tests/benchmarking
        pytest benchmarking.py

    - name: Store benchmark result
      uses: rhysd/github-action-benchmark@v1
      with:
        name: Python Benchmark
        tool: 'pytest'
        output-file-path: carball/tests/benchmarking/bench_output.json
        # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/td-p/26869/highlight/false
        github-token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        auto-push: true
        # Show alert with commit comment on detecting possible performance regression
        alert-threshold: '0%'
        comment-on-alert: true
        fail-on-alert: true