name: Benchmarking

on:
  push:
    branches: [ master, action-benchmark, integrate-boxcars]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Install/Update pip and wheel.
      run:
        python -m pip install --upgrade pip &&
        pip install wheel

    - name: Set-up and install protobuf.
      run: chmod 777 ./_travis/install-protoc.sh && ./_travis/install-protoc.sh 2.6.1

    - name: Install dependencies.
      run: pip install -r requirements.txt && pip install -r requirements-test.txt

    - name: Initialise.
      run: python init.py

    - name: Prepare benchmark.
      run: |
        pip install -r requirements.txt && pip install -r requirements-test.txt
        cd carball/tests/benchmarking
        echo === BENCHMARK DIRECTORY ===
        ls -lh
        echo ===========================

    - name: Run benchmark.
      run: |
        cd carball/tests/benchmarking
        pytest benchmarking.py

#    TO BE DONE.
#    - name: Store benchmark result(s).
