# This is a basic workflow to help you get started with Actions

name: DOC UPDATE
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dtracers-patch-2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    # setup protobuf
    - run: chmod 777 ./_travis/install-protoc.sh
    - name: Setup install
      run: "./_travis/install-protoc.sh 2.6.1"

    - name: Duplicate
      run: cd carball/generated/binaries && mkdir .libs && ls carball/generated/binaries && echo TRYING TO DUPLICATE && cp protoc .libs/protoc
#      if [ -f protoc ]; then cp protoc .libs/protoc fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt |
        python init.py

    - name: Create document
      run: python -m carball.tests.docs.data_frame_docs
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    
    - name: wiki-page-creator-action
      uses: Decathlon/wiki-page-creator-action@v2.0.0
      env:
        GH_PAT: ${{ secrets.GH_WIKI_EDIT_TOKEN }}
        ACTION_MAIL: saltie.calculated.gg@gmail.com
        ACTION_NAME: saltie
        OWNER: SaltieRL
        REPO_NAME: carball
        MD_FOLDER: carball/tests/docs
        SKIP_MD: df_methods.md, df_summary.md
