# This is a basic workflow to help you get started with Actions

name: DOC UPDATE
# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dtracers-patch-2 ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: wiki-page-creator-action
      uses: Decathlon/wiki-page-creator-action@v2.0.0
      env:
        GH_PAT: ${{ secrets.GH_WIKI_EDIT_TOKEN }}
        ACTION_MAIL: saltie.calculated.gg@gmail.com
        ACTION_NAME: saltie
        OWNER: SaltieRL
        REPO_NAME: carball
        MD_FOLDER: carball/tests/docs
